# Generated by Django 2.0.5 on 2018-05-23 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplDataRepresentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deliverie',
            new_name='Delivery',
        ),
        migrations.RenameModel(
            old_name='Matche',
            new_name='Match',
        ),
    ]
