# Generated by Django 2.0.5 on 2018-05-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplDataRepresentation', '0002_auto_20180523_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='match_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iplDataRepresentation.Match'),
        ),
    ]
