# Generated by Django 2.0.5 on 2018-05-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iplDataRepresentation', '0003_auto_20180523_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplDataRepresentation.Match'),
        ),
    ]
